//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class asiakas
{
    public string astunnus { get; set; }
    public string asnimi { get; set; }
    public string yhteyshlo { get; set; }
    public string maa { get; set; }
    public string postinro { get; set; }
    public string postitmp { get; set; }
    public Nullable<double> ostot { get; set; }
    public Nullable<short> asvuosi { get; set; }
}
